<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <!-- ProjectReference for now since Safaricom.Daraja isn't published to NuGet yet.
         Once it is, replace this with: <PackageReference Include="Safaricom.Daraja" Version="x.y.z" /> -->
    <ProjectReference Include="..\..\src\Safaricom.Daraja\Safaricom.Daraja.csproj" />
  </ItemGroup>

</Project>
